- name: Manage Services on Multiple Servers
  hosts: webservers
  become: yes
  vars:
    package_dict:
      webserver: apache2
      db: mariadb-server
  tasks:
    - name: Install multiple packages from dictionary
      apt:
        name: "{{ item.value }}"
        state: present
        update_cache: true
      loop: "{{ package_dict | dict2items }}"

    - name: Start multiple services from dictionary
      service:
        name: "{{ 'mysql' if item.key == 'db' else item.value }}"
        state: started
        enabled: yes
      loop: "{{ package_dict | dict2items }}"
