- name: Manage Multiple Packages on Servers
  hosts: webservers
  become: yes
  vars:
    package_list:
      - apache2
      - mariadb-server
  tasks:
    - name: Install multiple packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop: "{{ package_list }}"

    - name: Start multiple services
      service:
        name: "{{ 'mysql' if item == 'mariadb-server' else item }}"
        state: started
        enabled: yes
      loop: "{{ package_list }}"
