- name: Install Apache server
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Install Apache
      apt:
        name: "{{ package_name }}"
        state: present
        update_cache: yes
    - name: Start Apache
      service:
        name: "{{ package_name }}"
        state: started
        enabled: yes
